// ---------------------------------------------------------------------------
// Lightweight DO stub typing for v0.1.
// Proper types will be generated by `wrangler types` once the DO is deployed.
// ---------------------------------------------------------------------------

/** Shape of the RPC methods exposed by ChannelDO */
export interface ChannelDOStub {
  ingestEvent(raw: {
    channel_name: string;
    method: string;
    path: string;
    query: Record<string, string>;
    headers: Record<string, string>;
    remote_addr?: string;
    user_agent?: string;
    provider: { hint?: string; event_type?: string; delivery_id?: string };
    body: { encoding: 'utf8' | 'base64'; content_type?: string; data: string; size: number; truncated: boolean };
    summary?: { title: string; subtitle?: string };
  }): Promise<{ id: string; seq: number }>;

  getEvents(params: {
    limit?: number;
    afterSeq?: number;
    beforeSeq?: number;
    includeBody?: boolean;
    includeHeaders?: boolean;
  }): Promise<any[]>;

  clearEvents(): Promise<number>;
  getStatus(): Promise<{ connectedClients: number; lastSeq: number; eventCount: number }>;
  handleWebSocket(ws: WebSocket, clientType?: string, userAgent?: string): Promise<void>;
  closeAllClients(code?: number, reason?: string): Promise<void>;
}

/**
 * Helper: resolve a ChannelDO stub from the namespace.
 * Uses `as any` because Cloudflare's DurableObjectStub branded types
 * don't expose custom RPC methods until wrangler types are generated.
 */
export function getChannelStub(ns: DurableObjectNamespace, name: string): ChannelDOStub {
  const id = ns.idFromName(name);
  return ns.get(id) as unknown as ChannelDOStub;
}
